# -*- coding: utf-8 -*-
"""dolgozat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DzCIQ8DC9Jxt6BxAVTuE61QxyiqTfk4w
"""

f = open("ajanlatok.txt","r", encoding="utf-8")
l = []
for sor in f:
  l.append(sor.strip().split(";"))
print(*l)

print("Hány mátrai tájegységre vonatozó ajánlat található az input fájlban?")

with open("ajanlatok.txt","r") as file:
  szam = 0
  for a in file:
    if "Mátra" in a:
      szam += 1
print(f"2. feladat: {szam}db található")

print("Van-e az irodának téli, balatoni ajánlata?")
print(f"37. feladat: ")
van = False
for i in l:
  if i == van:
    van = True
print(f'Az irodának {"van" if van else "nincs"} téli balatoni ajánlata')

print("Igaz-e, hogy az minden ajánlat legalább 5 napos?")
print(f"45. feladat: ")
ajanlat = 0
for i in l:
  if i == ajanlat:
    ajanlat += 1
print(ajanlat)

volt = False
for i in l:
  if l == i:
    volt = True
  if volt == True:
    print("igaz, hogy minden ajánlat legalább 5 napos")
  else:
    print("Nem igaz az, hogy minden ajánlat legalább 5 napos")
    break

print("Hány forintba kerül a legdrágább ajánlat?")
print(f"54. feladat: ")
legnagyobb = 0
 
for f in l:
  if f == legnagyobb:
    legnagyobb = f
print(f"A legdrágább ajánlat pontos adatai: {f}")