# -*- coding: utf-8 -*-
"""MagyarMark2023_01_18(7.feladat).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13IQLoYKnX-ZzhHNmkXKXJ13jhrcFfvT9
"""

import math 
import random
def fgv(x):
  if math.sqrt(x) == 2 or math.sqrt(x) == 3 or math.sqrt(x) == 4 or math.sqrt(x) == 5 or math.sqrt(x) == 6 or math.sqrt(x) == 7 or math.sqrt(x) == 8 or math.sqrt(x) == 9 or math.sqrt(x) == 10:
    return(x)

szam = 0
l = [random.randint(1,100) for _ in range(1,100)]
print(l)

for i in l:
  if fgv(i):
    szam += 1
print(f"A függvény ennyi elemre igaz: {szam}")