# -*- coding: utf-8 -*-
"""MagyarMark_2022_11_17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5et69lwLwlCrhbd6KCm8XJTGtH2ICzQ
"""

f = open("adatok.txt","r", encoding="utf-8")
adatok = []
for sor in f:
  adatok.append(int(sor))
print(adatok)

print("1.feladat:")
db = 0
for i in range(len(adatok)):
  if adatok[i] % 10 == 0:
    db += 1
if db:
  print(f"A sorozatban: {db-1}db olyan szám található ami 1 és 10 közé esik")

print("2.feladat:")
db = False
for i in range(len(adatok)):
  if l[i] % 18 == 0:
    db = True
if db:
  print(f"Az első 18-al osztható szám indexe: {i}")
else:
  print("Nincs 18-al osztható szám a sorozatban")

print("3.feladat:")
print(f"A sorozatban található szám legkissebb indexe: {min(adatok)}")

print("4.feladat:")
van = False
for i in range(len(adatok)):
  if l[i] % 25 == 0:
    van = True
if van:
  print(f"Az utolsó 25-tel osztható szám: {i}. és annak négyzetgyöke: {i ** 2}.")

print("5.feladat:")