# -*- coding: utf-8 -*-
"""MagyarMárk_dolgozat_2022_10_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnv6Ych0mSaymf22fZUlLA9XwgRI25Fk
"""

import numpy as np
lista = []
a = 0
db = 0
eredmeny = 0
while eredmeny < 100:
  a = int(input("Számot: "))
  if a % 2 == 0:
    db = db + 1
    lista.append(a)
    eredmeny = np.prod(np.array(lista))
    continue
  else:
    print("nem páros")
print(f"{db}.db Számból jött ki a 100 vagy nagyobb eredmény! Számok:{lista}")