# -*- coding: utf-8 -*-
"""Magyar_Márk_3_Feladat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zKOhPbzbfE5It0k807KyEPCg6hJxJbKr
"""

class Torta:
  def __init__(self,kenvekrem = 0,emeletek = 0):
    self.emeletek = emeletek
    self.kenvekrem = kenvekrem

  def ujEmelet(self):
    emeletek = 0
    if emeletek == 0:
      print(f"{self.emeletek}")

  def kremmelMegken(self):
    kenvekrem = 0
    if kenvekrem == 0:
      return kenvekrem
      print(f"{self.kenvekrem}")

  def mennyiKaloria(self):
    emelet = 1000
    if emelet * 2:
      print(f"{emelet*2}")

  def __repr__(self):
    return f"<object.Torta>"

t1 = Torta("torta",1)
t2 = Torta("torta")
print(t1)
print(t2)
t1.ujEmelet()
t2.ujEmelet()
t1.kremmelMegken()
t2.kremmelMegken()
t1.mennyiKaloria()
t2.mennyiKaloria()